---
- name: "Yay | Checking Yay install"
  ansible.builtin.command: which yay
  register: yay_check
  ignore_errors: yes
  changed_when: false

- name: "Yay | Install dependencies"
  become: true
  community.general.pacman:
    name:
      - base-devel
      - git
    state: present
  when: yay_check.rc != 0

- name: "Yay | Downloading repo"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    clone: yes
    update: no
  become_user: nobody
  when: yay_check.rc != 0

- name: "Yay | Building & install..."
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  become_user: nobody
  when: yay_check.rc != 0

- name: "Yay | Removing temp files"
  file:
    path: /tmp/yay
    state: absent
  when: yay_check.rc != 0