- name: Setup dotfiles and apps
  hosts: localhost

  roles:
    - update-cache
    - additional-packages
    - yay
    - fonts
    - kitty
    - p10k
    - tmux
    - neovim
    # - bitwarden

  vars:
    additional_packages:
      - git
      - curl
      - unzip
      - zip
      - bitwarden
      - firefox
      - chromium
      - thunderbird
      - vscodium
