- name: Setup dotfiles and apps
  hosts: localhost

  roles:
    - update-cache
    - additional-packages
    - yay
    - fonts
    - kitty
    - p10k
    - tmux
    - neovim

  vars:
    additional_packages: # ⚠️ Ensure these packages are available in your distribution's repositories, otherwise the playbook may fail.
      - git
      - curl
      - unzip
      - zip
      - tree
      - vim
      - neofetch
      - bitwarden
      # - thunderbird
