---
- name: "Arch | Update pacman cache"
  become: true
  community.general.pacman:
    update_cache: true

- name: "Arch | Install Neovim"
  become: true
  community.general.pacman:
    name: neovim
    state: present

