---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "LazyVim | Check if LazyVim is already installed (lazyvim.json exists)"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/nvim/lazyvim.json"
  register: lazyvim_installed

- name: "LazyVim | Remove existing Neovim config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: absent
  when: not lazyvim_installed.stat.exists | default(false)

- name: "LazyVim | Clone LazyVim starter config"
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter.git
    dest: "{{ ansible_user_dir }}/.config/nvim"
    depth: 1
  when: not lazyvim_installed.stat.exists | default(false)

- name: "LazyVim | Remove .git folder from config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim/.git"
    state: absent
  when: not lazyvim_installed.stat.exists | default(false)
