---
- name: "Fonts | Checking fonts folder"
  stat:
    path: ~/.local/share/fonts
  register: powerline_fonts_dir

- name: "Fonts | Checking powerline fonts presence"
  find:
    paths: "{{ powerline_fonts_dir.stat.path | default('~/.local/share/fonts') }}"
    patterns: '*Powerline*.ttf'
  register: powerline_fonts_found
  when: powerline_fonts_dir.stat.exists

- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists and (powerline_fonts_found.matched | default(0)) == 0
